### ISSUE TITLE
EPIC: Create IG routes for OBIE API v3.1.8

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#114]
### Description
Epic task to implement routes in IG for all [OBIE read/write APIs version v3.1.8](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/profiles/read-write-data-api-profile)

---
#### [Account and Transaction](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/profiles/payment-initiation-api-profile)

<details>
<summary>Account and Transaction Tasks (label 'api: accounts')</summary>

_[Account access Consents](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/account-access-consents.html)_
- [x] POST /account-access-consents **DONE**
- [x] GET /account-access-consents/{ConsentId} **DONE**
- [x] DELETE /account-access-consents/{ConsentId} **DONE**

_[Accounts](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Accounts.html)_
- [x] GET /accounts **DONE**
- [x] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/111

_[Balances](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Balances.html)_
- [x] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/112
- [x] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/113

_[Transactions](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Transactions.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/115
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/116

_[Beneficiaries](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Beneficiaries.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/117
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/118

_[Direct Debits](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/direct-debits.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/119
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/120

_[Standing Orders](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/standing-orders.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/121
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/122

_[Products](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Products)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/123
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/124

_[Offers](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Offers.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/125
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/126

_[Parties](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Parties.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/127
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/128
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/129

_[Scheduled Payments](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/scheduled-payments.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/130
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/131

_[Statements](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Statements.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/132
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/133
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/134
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/135
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/136
</details>

---

#### [Payment initiation](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/profiles/payment-initiation-api-profile)

<details>
<summary>Payment initiation Tasks (label 'api: payments')</summary>

_[Domestic payments Consent](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/domestic-payment-consents.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/137
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/138
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/139

_[Domestic Payments](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/domestic-payments.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/140
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/141
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/142

_[Domestic Scheduled Payment Consent](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/domestic-scheduled-payment-consents.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/143
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/144

_[Domestic Scheduled Payment](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/domestic-scheduled-payments.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/145
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/146
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/147

_[Domestic Standing Order Consents](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/domestic-standing-order-consents.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/148
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/149

_[Domestic Standing Orders](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/domestic-standing-orders.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/150
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/151
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/152

_[International Payment Consents](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/international-payment-consents.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/153
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/154
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/155

_[International Payments](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/international-payments.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/156
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/157
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/158

_[International Scheduled Payment Consents](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/international-scheduled-payment-consents.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/159
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/160
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/161

_[International Scheduled Payments](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/international-scheduled-payments.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/162
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/163
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/164

_[International Standing Order Consents](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/international-standing-order-consents.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/165
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/166

_[International Standing Orders](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/international-standing-orders.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/167
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/168
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/169

_[File Payment Consents](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/file-payment-consents.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/170
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/171
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/172
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/173

_[File Payments](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/file-payments.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/174
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/175
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/176
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/177
</details>

---

#### [Confirmation of funds](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/profiles/confirmation-of-funds-api-profile)

<details>
<summary>Confirmation of funds Tasks (label 'api: confirmation of funds')</summary>

_[Funds Confirmation Consent](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/cbpii/funds-confirmation-consent.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/178
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/179
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/180

_[Funds Confirmation](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/cbpii/funds-confirmation.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/181
</details>

---

#### [Variable recurring Payments](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/profiles/vrp-profile)

<details>
<summary>Variable recurring Payments Tasks (label 'api: vrp payments')</summary>

_[Domestic VRP Consents](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/vrp/domestic-vrp-consents.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/182
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/183
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/184
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/185

_[Domestic VRPs](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/vrp/domestic-vrps.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/186
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/187
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/188
</details>

---

#### [Event Notification](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/profiles/event-notification-api-profile)

<details>
<summary>Event Notification Tasks (label 'api: events')</summary>

_[Even Notification Subscription](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/profiles/event-notification-subscription-api-profile.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/189
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/190
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/191
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/192

_[Callback URL](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/profiles/callback-url-api-profile.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/193
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/194
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/195
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/196

_[Real Time Event Notification](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/profiles/real-time-event-notification-api-profile.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/197

_[Aggregated Polling](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/profiles/aggregated-polling-api-profile.html)_
- [ ] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/198
</details>

**Comment by jorgesanchezperez** [comment]
Currently we use zenhub to manage the project backlog and the sprint backlog.
We not need this epic anymore.
