### ISSUE TITLE
Update dependencies to remove critical and high security issues

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1192]
Merge dependabot PRs for the following repositories;
- [ ] https://github.com/SecureApiGateway/secure-api-gateway-parent
- [ ] https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-common
- [ ] https://github.com/SecureApiGateway/secure-api-gateway-ob-uk
- [ ] https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rs
