### ISSUE TITLE
Provide the remaining simulated RS endpoints for the Read/Write API

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#14]
## Story

As an Open Banking customer
I want to be able to test my services against a full mock implementation of the OB Read/Write API
so that I can be confident my services will work when I switch to a real bank implementation

## Acceptance criteria

- The full Read/Write API (accounts, payments, events, funds) is implemented.
- All versions from 3.0 to 3.1.6 are supported.

## Tasks

- [x]  Copy the OB API controller classes from rs-mock-store within openbanking-aspsp.
- [x]  Replace references to ConsentMetricService in each controller with an appropriate log statement.
- [x]  Add a mechanism to extract required information (such as the Tpp (or client) ID) from a JWT.
- [x]  Remove any references to TppRepository and Tpp from the controller classes.
- [x]  Ensure the controller classes use constructor based injection.

### Release Notes

Affected App: securebanking-openbanking-aspsp-simulator
