### ISSUE TITLE
Support OBIE Read/Write API v4 - x type of payment API (template)

### ISSUE THREAD

**Issue by frlaura-jianu** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1487]
### Introduction

This will allow users to blah, blah
OBIE Read/Write API v4 - x type of payment support

### User Story

As a TPP I want to be able to create an x type of payment.

### Product requirements (optional)

- the TPP will be able to initiate an x type of payment
- the TPP will be able to submit an x type of payment
- the TPP will be able to get the payment status
- the TPP will be able to get the user funds status
- the TPP will be able to get the x type of payment status
- test coverage should be provided across all components (unit/Postman/functional tests)
etc.

### X type of payment API

- #### Data model
  - [x] generate the OB data model classes (link #issueNo.)
  - [ ] create/update converters (link #issueNo.)
  etc.

- #### RS
  - [ ] add the new OB controllers (link #issueNo.)
  - [ ] add unit tests for the new controllers (factories, etc.) (link #issueNo.)
  etc.

- #### RCS
  - [ ] design the new consent state model (link #issueNo.)
  - [ ] add RCS support (Consent Store, etc.) (link #issueNo.) 
  etc.

- #### Test coverage
   - [ ] add the mandatoryFieldsOnly methods (link #issueNo.)
   - [ ] add functional test support
   - [ ] add Postman test support

### Acceptance Criteria

The following should be provided during each implementation phase:
- [x] unit test support
- [ ] functional test support
- [ ] Postman test support

Also ensure that:
- [ ] the test suite passes for each type of tests
- [ ] the TPP can perform an end2end API flow
