### ISSUE TITLE
cdk / identity cloud platform client library api for secure banking access toolkit

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#204]
## Story

As a developer of the Secure Banking Access Toolkit
I want to have a generic and transversal `cdk/identity cloud platform` api client library isolated in his own repository
so that I can provide a functionalities to consume  the `cdk/identity cloud platform` apis independently of the open banking specifications.

## Acceptance criteria
- New repository to store the library
- `cdk/identity cloud platform` api client library implemented.

## Tasks
- [x] Create `cdk/identity cloud platform` api client library. https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rcs/pull/39
      - Library created on [securebanking-openbanking-uk-rcs](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rcs)
      - Currently supported for uk openbanking objects
- [ ] Create new repository for `cdk/identity cloud platform` api client library.
- [ ] Refactoring of the existing client library when moved to the new repository to make a generic library
- [ ] Update dependent projects with the new location of the client library.

### Release Notes

Affected Apps:
* securebanking-openbanking-uk-rcs

**Comment by BohoCode** [comment]
Is this to support removing duplicate code from the RS and RCS??

**Comment by BohoCode** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/204?planning-poker) with Zenhub @dbadham-fr @jorgesanchezperez
