### ISSUE TITLE
CDK instance configuration: jwt Signature Verification fails, wrong consent response signing algorithm

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#208]
**Describe the bug**
The signing algorithm to be used by the provider when verifying the signature of the consent response JWT received from the Remote Consent Service doesn't match with the algorithm expected set in the remote consent agent properties.
An jwt signature error is raised validating the jwt request decision.

**To Reproduce**
Run the account access consent flow.

**Expected behaviour**
Account access consent flow works properly end to end.

**Current behaviour**
```shell
"level":"WARN","thread":"http-nio-8081-exec-9","mdc":{"transactionId":"83c39767-b7c8-4f7f-847b-06938ab6d56f-64929"},"logger":"org.forgerock.openam.jwt.JwtSignatureVerificationHandler","message":"The JWS signature algorithm 'PS256' is not the one expected 'HS256'.","context":"default"}
```

**Task**
Some properties in remote consent need to be reconfigured to use the proper signature properties:
- [x] Consent Request signing algorithm set to `PS256` instead of `HS256`
- [x] Public key selector set to `JWTs` instead of `JWKs_URI`
- [x] Json Web Key set with the content of `https://obdemo.dev.forgerock.financial/jwkms/apiclient/jwks`
