### ISSUE TITLE
Split initialiser operations: Create populate PSU data pod for namespaces

### ISSUE THREAD

**Issue by jsanhc** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#226]
### Description
Related with the issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/225
We have applied a patch in [fidc-initializer](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-fidc-initializer) to populate the PSU user data to RS service for each namespace but te correct way to do that is to have a dedicated pod deployed in each namespace to split the initialisers and avoid mixing them.

### Tasks
- [ ] Check `psu` `userId` from CDK or create it if necessary
- [ ] Check if `RS service` has data for this `userId`
- [ ] Populate `psu` user data if necessary
- [ ] Create a kubernetes cronjob to run the pod by interval time.

**Comment by jorgesanchezperez** [comment]
The task issue to implement that was: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/294
