### ISSUE TITLE
Initialise CDK and Cloud platform with the same configuration

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#229]
## Description
As a developer I want to have the same configuration in CDK and the Cloud so that I can test them in the same way and with the same data.

## Issues related
- https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/226
## Tasks
- [x] Check the difference between CDK initialiser and Cloud platform initialiser
- [x] Is it feasible have the same configuration using the same initialiser?
   - [x] Implement the same configuration by initialiser in CDK and Cloud platform
   - [x] Populate the user data for test purposes
