### ISSUE TITLE
RCS_UI: Field `sharedAccounts` to `accountIds` when send consent decision to RCS backed

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#237]
**Describe the feature/improvement**
When user accept the consent and the consent decision is send to RCS backend the field array that contains the accounts is `sharedAccounts` and RCS backend map this field into `accountIds` in the consent decision object.

RCS-UI could send the accounts directly in the field `accountIds` instead of in the field `sharedAccounts` so the RCS backend will map directly this field without specific Json annotations to map it.

**Tasks**
- [x] RCS-UI: Modify the field `sharedAccounts` to `accountsIds`
- [x] RCS backend: Modify the `consentDetailsRequest` to map directly the `accountId` field received from RCS-UI. 
- [x] Ensure that functional tests passed with no fails.

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/237?planning-poker) with ZenHub @andra-racovita @mariantiris
