### ISSUE TITLE
AISP Evaluation policy

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#240]
**Describe the bug**
The script to evaluate the AISP policy set `grantedAccounts` and `grantedPermissions` as attributes in the response to pass  these attributes to the route `12 - Open Banking Account Access multiple routes` to add these attributes in the headers `x-ob-account-ids` and `x-ob-permissions`  to comply with the headers expected by the Account access apis.

The issue happens when the tpp request the account access for party, that api expected the header `x-ob-user-id` that isn't added in the evaluation policy script as attribute and then the request is rejected with the below error:
```json
{
    "Code": "400",
    "Id": "60635669afe350de9971f421ae51591a",
    "Message": "[Status: 400 Bad Request]",
    "Errors": {
        "ErrorCode": "UK.OBIE.Header.Missing",
        "Message": "Missing request header 'x-ob-user-id' for method parameter of type String"
    }
}
```

**To Reproduce**
Request the api `/aisp/party` and check the error response.

**Expected behaviour**
The api response with the party json object.
```json
{
    "Data": {
        "Party": {
            "PartyId": "462b04d5-31d5-4f10-8885-b41b8a559414",
            "PartyNumber": null,
            "PartyType": null,
            "Name": "7b78b560-6057-41c5-bf1f-1ed590b1c30b",
            "FullLegalName": null,
            "LegalStructure": null,
            "BeneficialOwnership": null,
            "AccountRole": null,
            "EmailAddress": null,
            "Phone": null,
            "Mobile": null,
            "Relationships": null,
            "Address": null
        }
    },
    "Links": {
        "Self": "http://localhost:8080/open-banking/v3.1.8/aisp/party",
        "First": null,
        "Prev": null,
        "Next": null,
        "Last": null
    },
    "Meta": {
        "TotalPages": 1,
        "FirstAvailableDateTime": null,
        "LastAvailableDateTime": null
    }
}
```

### Tasks
- [x] Add a filter query `?_fields=_id,_rev,Data,Risk,user/_id,accounts,apiClient/_id` in the method `getIntent` to complete the URI when evaluation script get the managed object to obtain the objects related user and apiClient.
- [x] Add the user id as a attribute in the response of evaluation script in the same way that is set the `grantedAccounts` or `grantedPermissions`
- [x] Add the argument header `x-ob-user-id` in the route filter `ScriptableFilter` and modify the groovy script `TranslateAccountsResource.groovy` to add the new header `x-ob-user-id`
- [x] Run the tests to ensure that all works properly.
