### ISSUE TITLE
[issue]: Nginx: 400 Request Header Or Cookie too Large

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#258]
### Components

Dev Operations

### Task Story (optional)

As a platform consumer, I want the platform supports `large client headers` so that I can POST a request resource with large  header signature.

### Describe de task

Upgrade the [nginx helm chart](https://github.com/ForgeCloud/sbat-infra/tree/master/cluster/nginx) to sets the maximum number and size of buffers used for reading large client request header.
   - [ ] Review the **additional context** documents to decide which proper values can be optimal for the platform.
   - [ ] Add the property `large-client-header-buffers: "number  size"`.

### Acceptance criteria

- [ ] The platform accepts large client headers.

### Documents
- https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#large-client-header-buffers
- https://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers

### History
- https://github.com/ForgeCloud/ob-deploy/issues/690
