### ISSUE TITLE
RS Simulator: switch to parent pom and uk-datamodel from securebanking-common

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#27]
## Story

As a member of ForgeRock's Open Banking Team
I want the ASPSP simulator to use the parent pom and common modules
So that it is easier to manage the project's dependencies and reduce avoid duplication

## Acceptance criteria
* The `securebanking-openbanking-aspsp` project's main pom extends the `securebanking-parent` pom
* `securebanking-openbanking-aspsp` imports the `securebanking-common` bom
* `securebanking-openbanking-aspsp-simulator` imports `securebanking-common-openbanking-uk-datamodel`
* The `securebanking-openbanking-aspsp-model` module has been removed from `securebanking-openbanking-aspsp`

## Tasks

- [ ] Move 3rd party libraries into parent pom
- [ ] Fix dependencies issues (e.g. JUnit 4) in securebanking-common
- [ ] Copy any recent changes to `securebanking-common-openbanking-uk-datamodel` to `securebanking-common-openbanking-uk-datamodel`
- [ ] Remove the `securebanking-common-openbanking-uk-datamodel` module and use `securebanking-common-openbanking-uk-datamodel` instead (via `securebanking-common-bom`)

### Release Notes

Affected App: securebanking-openbanking-aspsp-simulator
