### ISSUE TITLE
Rename securebanking-openbanking-demo to securebanking-openbanking-uk-gateway

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#300]
the use of the word demo gives the wrong message. Further more it's really not descriptive. Renaming now will likely be painful, but not as painful as later. Let's do this now before it gets spread throughout the docs and customers start cloning it! 

### Tasks
- [x] Rename the repository with the new name `securebanking-openbanking-uk-gateway`
- [x] Update pipelines and actions with the new repository name
- [x] Update readme files
- [x] Update wiki references to the new repository name

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/300?planning-poker) with ZenHub @andra-racovita @mariantiris
