### ISSUE TITLE
Move source declaration in filter to a separated script file

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#308]
### Components

IG

### Task Story (optional)

As the developer, I want to move the declare groovy source from filter to a separated file so that all script source will be in his own file.

### Describe the task
Create script files for the in-route scripts.
For example this in-route script from [31-ob-payment-submission] (https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/c2e090f8df0ef3a40101353424df06347b8189b6/config/7.0/obdemo-bank/ig/routes/routes-service/31-ob-payment-submission.json#L124).

### Acceptance criteria
- [x] Script source moved to a separated script file.
- [x] The routes work properly and with the same expected behavior.
- [x] All tests pass

### Additional Context (optional)

**Comment from `Dom Reed`**
There are a handful of ScriptableHandlers in there too. I’m assuming it makes sense to document them and which routes use them similar to ScriptableFilters?

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/308?planning-poker) with ZenHub @andra-racovita @BohoCode @dbadham-fr @mariantiris @joycegilding-forgerock
