### ISSUE TITLE
Managed objects: Miss fields for domesticPaymentIntent

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#310]
### Description
We miss to add some fields in `domesticPaymentIntent` to comply with the consent object defined in specs.
- https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/domestic-payment-consents.html

### Missed fiels
- Data/ReadRefundAccount [0..1]
- Data/SCASupportData [0..1]
- Data/Charges [0..*]

## Tasks
- [x] Add missed fields on IDM object
- [x] Update the patch consent on RCS to set the missed fields on the intent object
- [x] Update postman
- [x] Update functional tests coverage

## Acceptance criteria
- [x] The tpp is able to set the missed fields and the values are set in IDM object
- [x] The consent is returned with the missed fields set
- [x] All tests coverage passed with the new missed fields.
