### ISSUE TITLE
RESTful API documentation (Swagger) for RS (Bank simulation)

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#318]
### Introduction

This feature will provide to customers to  the RESTful API documentation of RS APIs implementation and allow them build their own RS bank gateway to integrate it with their bank mainframe and live bank data resources.

- The visual documentation making it easy for back end implementation and client side consumption.

### Repositories affected
- [securebanking-openbanking-uk-rs](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs)
- [securebanking-swagger-ui](https://github.com/SecureBankingAccessToolkit/securebanking-ui/tree/master/securebanking-swagger-ui)

### User Story

As SBAT **customer**, I want to have access to `RESTful API documentation` of SBAT RS Bank simulation service so that I can visualise and interact with the API’s resources without having any of the implementation logic in place and have a documentation reference to build my own RS Bank gateway to integrate it with live bank resources.

### Product requirements (optional)

- [ ] RS OpenApi implementation (swagger) to generate the RESTful API documentation.
- [ ] RS OpenApi/swagger descriptor consumption endpoint 
- [ ] Swagger UI service as consumer of OpenApi/swagger descriptor generated by RS

### Design requirements (optional)

- Avoid generate APIs that are not helpful for **customer** point of view:
    - Only helpful APIs to implement their own Bank gateway resources
    - Avoid generate annoying noise documentation (headers, parameters, etc)

### Scope

- Generate RS RESTful API reference documentation (OpenApi/Swagger)
- Publish RS OpenApi descriptor endpoint
- Swagger UI service OpenApi descriptor consumer

### Acceptance Criteria

- [ ] RS generate the proper API documentation OpenApi/Swagger descriptor
- [ ] RS publish the endpoint to consume the OpenApi descriptor
- [ ] Swagger UI consume the OpenApi descriptor properly
- [ ] Swagger UI present the RS API documentation properly
