### ISSUE TITLE
Generate RS RESTful API reference documentation

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#319]
## Description
Generate RS (Bank simulation) RESTful API reference documentation.

## Tasks
- [x] RS OpenApi implementation (swagger) to generate the RESTful API documentation.
- [x] Filter to publish only `/open-banking/` context endpoints
   - `Docket(..).paths(PathSelectors.regex("/open-banking/.*"))`
- [x] RS OpenApi/swagger descriptor endpoint `/api-docs`

## Acceptance Criteria
- [x] RS generate the proper API documentation OpenApi/Swagger descriptor
- [x] RS publish the endpoint `/api-docs` to consume the OpenApi descriptor

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/319?planning-poker) with ZenHub @andra-racovita @mariantiris

**Comment by jorgesanchezperez** [comment]
Reopened:
**Reason**: Currently swagger displays some apis that are in the same taxonomy in different tags.
**Task**: Fix APIs tag operations to display properly by group the APIs operations.
