### ISSUE TITLE
Swagger UI to publish RS API documentation

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#320]
## Description
Generate RS (Bank simulation) RESTful API reference documentation.

## Tasks
- [x] Swagger UI service consume the OpenApi/swagger descriptor generated by RS
- [x] Visualise OpenApi reference documentation on Swagger UI 

## Acceptance Criteria
- [x] Swagger UI consume the OpenApi descriptor properly
- [x] Swagger UI present the RS API documentation properly

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/320?planning-poker) with ZenHub @andra-racovita @mariantiris
