### ISSUE TITLE
As a TPP I want to be able to create a domestic standing order payment.

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#321]
### Introduction

This feature allow TPP to create a domestic standing order payment

### User Story

As a TPP I want to be able to create a domestic standing order payment.

### Product requirements (optional)

- The TPP be able to initiate a domestic standing order payment
- The TPP be able to submit domestic standing order payment
- The TPP be able to get the initiation status
- The TPP be able to get the domestic standing order payment status
- The Domestic standing order APIs have test coverage (postman and functional tests) for all cases of operations

### Domestic standing order consent/intent
- **Platform (configuration, initialiser)**
    - [x] #322
- **IG**
    - [x] #323
    - [x] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/349
    - [x] https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/340
- **RCS Backend**
    - [x] #328
    - [x] #327
- **RCS User interfaces**
    - [x] #326
    - [x] #325
### Domestic standing order submitting
- **Platform (configuration, initialiser)**
    - [x] #329
- **IG**
    - [x] #324
- **RS backend**
    - [x] #330
    - [x] #331
#### Tests and performance
- **SBAT Postman coverage**
    - [x] #332
    - [x] #335
- **SBAT functional tests (uk spec) coverage**
    - [x] #333
    - [x] #334

### Acceptance Criteria

- [x] All Domestic standing order consent is implemented and have the proper unit tests and integration tests coverage
- [x] All implementation have:
    - [x] Postman tests coverage
    - [x] Functional tests coverage
- [x] All domestic standing order consent postman tests pass
- [x] All functional tests domestic standing order consent pass
- [x] All domestic standing order submit and get details postman tests pass
- [x] All domestic standing order submit and get details functional tests pass
