### ISSUE TITLE
Remove consent functionality from the RS simulator and add validation

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#33]
As an Open Banking customer
I want the RS simulator to perform basic validation
so that I can be confident only valid payments are created

## Acceptance criteria
- A series of validations (e.g. "Risk and Initiation" etc.) are performed when a request to save a Domestic Payment is received.
- No knowledge of payment consents will be required by the simulator.

## Tasks
- [x] Remove payment consents related code.
- [x] Add required validation: verifyIdempotencyKeyLength() & verifyRisk()
- [x] Change implementation of `getDomesticPaymentConsentsConsentIdFundsConfirmation` to be independent of consents.

### Release Notes

Affected App: securebanking-openbanking-aspsp-simulator
