### ISSUE TITLE
Implementation `GET domestic standing order payment status details` (NOT IMPLEMENTED YET)

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#331]
### Description
Currently the no-mandatory API `GET /domestic-standing-orders/{DomesticStandingOrderId}/payment-details` isn't implemented yet.

**Ref:** https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/domestic-standing-orders.html

### Task
- [x] Implement Get domestic standing orders payment details [Here - RS](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs)
- [x] Add functional tests coverage
- [x] Add postman request tests coverage
- [x] Add Payment details Uri for Domestic Standing Order in [OBApiReference](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs/blob/master/securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/OBApiReference.java).

### Acceptance criteria
- [x] Get domestic standing orders payment details has been implemented
- [x] All functional tests coverage pass
- [x] All postman tests coverage pass

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/331?planning-poker) with ZenHub @andra-racovita @mariantiris
