### ISSUE TITLE
Create functional tests coverage: submit domestic standing order

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#334]
### Description
Implement the proper functional tests to cover the domestic standing orders submit resource flow [Here](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-functional-tests)
### Tasks
  - [x] Test coverage domestic standing orders submission with all fields
  - [x] Test coverage domestic standing orders submission with only mandatory fields
  - [x] Test coverage domestic standing orders submission expected errors
  - [x] Add gradle group task to run only the domestic standing orders tests v3.1.8
### Acceptance criteria
- [x] All current functional tests pass.
- [x] The `Domestic standing orders` functional tests pass.
- [x] As a developer I can run the a task to run only the `domestic standing orders` functional tests v3.1.8
