### ISSUE TITLE
Add Get Accounts functionality to RS simulator

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#36]
## Story

As a TPP
I want to be able to retrieve accounts from the ASPSP simulator
so that I can provide account related information to PSUs

## Acceptance criteria

- It is possible tor retrieve accounts from the Accounts API
- Only versions 3.1.3 onwards are supported initially

## Tasks

- [x] Add Controller classes and interfaces.
- [x] Use existing Account repository.
- [x] Implement SpringBoot test to verify functionality.
- [x] Add Data generation API classes.

### Release Notes

Affected App: securebanking-aspsp-simulator
