### ISSUE TITLE
Create functional tests coverage: submit International payment

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#373]
### Description
Implement the proper functional tests to cover the international payment submit resource flow [Here](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-functional-tests)
### Tasks
  - [x] Test coverage international payment submission with all fields
  - [x] Test coverage international payment submission with only mandatory fields
  - [x] Test coverage international payment submission expected errors
  - [x] Add gradle group task to run only the international payments tests v3.1.8
### Acceptance criteria
- [x] All current functional tests pass.
- [x] The `international payments` functional tests pass.
- [x] As a developer I can run the a task to run only the `international payments` functional tests v3.1.8
