### ISSUE TITLE
Restructure securebanking repositories

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#38]
## Story

As a Developer on the securebanking toolkit project
I want the securebanking repositories clearly organised
so that I'm familiar with the structure and know where to look for code

## Acceptance criteria

- A new securebanking-openbanking-uk multi-module project contains "common" code, including the obie and forgerock datamodels, plus other shared code.
- A new securebanking-openbanking-uk-rs multi-module project contains code that belongs to the Resource Server aspect of the Secure Banking Open Banking project, including a RS Simulator.
- A skeleton securebanking-openbanking-uk-rcs multi-module project contains code that belongs to the Remote Consent Server aspect of the Secure Banking Open Banking project.

## Tasks
- [x] Create the following modules within securebanking-openbanking-uk:
- - [x] `securebanking-openbanking-uk-bom`
- - [x] `securebanking-openbanking-uk-common`
- - [x] `securebanking-openbanking-uk-obie-datamodel`
- - [x] `securebanking-openbanking-uk-forgerock-datamodel`
- - [x] `securebanking-openbanking-uk-error`
- [x] Create the following modules within securebanking-openbanking-uk-rs:
- - [x] `securebanking-openbanking-uk-rs-obie-api`
- - [x] `securebanking-openbanking-uk-rs-backoffice-api`
- - [x] `securebanking-openbanking-uk-rs-simulator-admin-api`
- - [x] `securebanking-openbanking-uk-rs-simulator`
- - [x] `securebanking-openbanking-uk-rs-simulator-app`
- [x] Create the following modules within securebanking-openbanking-uk-rcs:
- - [x] `securebanking-openbanking-uk-rcs-api`
- - [x] `securebanking-openbanking-uk-rcs-server`
- - [x] `securebanking-openbanking-uk-rcs-app`
 
### Release Notes

Affected App:
- securebanking-openbanking-uk-rs-simulator
- securebanking-openbanking-uk-rcs
