### ISSUE TITLE
Securebanking-core: CORS error when Swagger app request the swagger descriptor to RS service

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#381]
### Components

Core library

### Describe the issue

**CORS error due to browser's same origin policy**
- The browser block the request, and Is not be able to see the response of the request.

>[CORS] (Cross-Origin Resource Sharing) is a mechanism that allows restricted resources on a web page to be requested from another domain outside the domain from which the first resource was served

### User Story (optional)

As the developer, I want to be able load the swagger api document descriptor in the swagger application so that the customer will be able to access the API Rest documentation through swagger application.

### Acceptance criteria (optional)

- [x] #382
- [x] #383
- [x] #384
- [x] #385
- [x] #386
- [x] #387
- [x] #388
- [x] #389
- [x] CORS error policy is fix when RCS-ui call RCS backend
- [x] CORS error policy is fix when Swagger-ui call RS backend
- [x] The swagger application load properly the swagger api document descriptor
- [x] The API rest documentation is published

### Additional Context (optional)

Currently the CORS policy error has been fixed in RCS implementing a `CorsFilter` to build properly the headers expected by the browser when a resource is served from a different domain it has been requested.

### Code solution approach (optional)

Currently the CORS policy error happens between Swagger app and RS backend, the solution must be the same implemented in RCS but we need to avoid source duplications and following this criteria we decide to do the below changes:
- Create a the new repository `securebanking-core` to centralise the secure banking core libraries implementations
- Move the `CorsFilter` implemented in RCS to this new library repository
- Update RCS and RS to used the new libraries as a dependency and then the `CorsFilter` can be injected as a core component
