### ISSUE TITLE
Migrate updated K8S Api's to v1.22

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#390]
We're seeing warnings from GKE that we need to update APIs to v1.22 compliant APIs. Not doing this will result in deployment failures when K8S updates to v1.22

![image](https://user-images.githubusercontent.com/1516395/177512504-02c60d52-70f5-41a5-9455-668b692d33a0.png)

# Tasks
## Update Mutating Webhook
- [x] Update `mutating-webhook go code and helm charts to use v1 APIs`
### Deprecation warnings
- admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+
- cert-manager.io/v1alpha2 Certificate is deprecated in v1.4+, unavailable in v1.6+; use cert-manager.io/v1 Certifica
te
- cert-manager.io/v1alpha2 Issuer is deprecated in v1.4+, unavailable in v1.6+; use cert-manager.io/v1 Issuer

## Update Argo CD deployment
The argo documentation is unclear as to which versions of argo support which k8s versions. The only errors that we can currently identify are deprecation warnings relating to a custom ingress that we add to the argo installation, which is simple to fix.

- [x] Update argo ingress definition to v1
- [x] Test current Argo CD version on k8s 1.22

### Deprecation warnings
- extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

## Update cert-manager deploy
Currently we are using version: 1.3.0 which supports up to k8s 1.21, update cert-manager to the latest version 1.8.2
- [x] Update cert-manager to 1.8.2

## Update kubernetes-external-secrets
- [x] Update kubernetes-external-secrets 6.4.0 => 8.5.5
### Deprecation warnings
- apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition                                                                                                                          
- rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole                                                                                                                                          
- rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding 

## Update prometheus
- [x] Update prometheus 16.1.2 => 38.0.2
### Deprecation warnings
- policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+                                    
- networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress 

## Update forgeops
Currently we are deploying forgeops 7.1.0, 2 ingresses are deployed which use the deprecated API.
Issue #339 identifies that 7.1.2 has a fix for this

- [x] Fix issue #339

### Deprecation warnings
- Warning: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

## Fix securebanking-ui helm chart
- [x] Update Ingress to v1

## Update ingress-nginx
The current version is calling deprecated webhook APIs
- [x] Update ingress-nginx 3.25.0 => 4.2.0

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/390?planning-poker) with ZenHub @dbadham-fr @frlaura-jianu @mariantiris @BohoCode
