### ISSUE TITLE
RS backend: implementation `GET /international-scheduled-payments/{InternationalScheduledPaymentId}/payment-details`

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#411]
### Description
Currently the no-mandatory API `GET /international-scheduled-payments/{InternationalScheduledPaymentId}/payment-details` isn't implemented yet.

**Ref:** https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/international-scheduled-payments.html#get-international-scheduled-payments-internationalscheduledpaymentid-payment-details

### Task
- [x] Implement Get international scheduled payment details [Here - RS](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs)
- [x] Add functional tests coverage
- [x] Add postman request tests coverage
- [x] Add Payment details URI for International scheduled payment details in [OBApiReference](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs/blob/master/securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/OBApiReference.java).

### Acceptance criteria
- [x] Get international payment details has been implemented
- [x] All functional tests coverage pass
- [x] All postman tests coverage pass
