### ISSUE TITLE
Functional test coverage: international scheduled payment consent

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#417]
### Description
Implement the proper functional tests to cover the international scheduled payment consent flow [Here](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-functional-tests)
### Tasks
  - [x] Test coverage international scheduled payment submission with all fields
  - [x] Test coverage international scheduled payment submission with only mandatory fields
  - [x] Test coverage international scheduled payment submission expected errors
  - [x] Add gradle group task to run only the international scheduled payments tests v3.1.8
### Acceptance criteria
- [x] All current functional tests pass.
- [x] The `international scheduled payments` functional tests pass.
- [x] As a developer I can run the a task to run only the `international scheduled payments` functional tests v3.1.8
