### ISSUE TITLE
RS backend: validate and calculate consent response fields

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#423]
### Introduction

The Payment Initiation API Profile describes the flows and common functionality for the Payment Initiation API, which allows a Payment Initiation Service Provider ('PISP') ([documentation](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/profiles/payment-initiation-api-profile.html#overview))

When a TPP starts a payment initiation some elements to build the response needs to be calculated by the ASPSP.

The response of a payment initiation contains the original payload with additional elements, some of these elements need to be calculated by the ASPSP, and the ASPSP need to validate some other elements from the original payload before calculate  the additional elements to build the response. 

These calculated elements are related with the payment initiation and for that reason will be necessary patch the original intent object with these new calculated elements. 

**Examples calculated elements and validations**
- Charge ([OBCharge2](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/profiles/payment-initiation-api-profile.html#obcharge2)): Set of elements used to provide details of a charge for the payment initiation.

**International Payments**
- Exchange Rate ([OBExchangeRate2](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/international-payment-consents.html#obexchangerate2)): Further detailed information on the exchange rate that has been used in the payment transaction.
    - Exchange rate behaviour:
        - An ASPSP must respond to an Agreed RateType request.
        - An ASPSP may respond to an Actual RateType request or may reject the request.
        - An ASPSP may respond to an Indicative RateType request or may reject the request.
        - An ASPSP must reject the international-payment-consent request if the specified Initiation/ExchangeRateInformation cannot be fulfilled.

### User Story

As a Customer, I want to be able calculate the response elements for payment initiation and patch the payment consent initiation object with the calculated elements so that I can comply with the response expected by the TPP and keep the payment consent intent object up to date.

### Product requirements
**Introduction**
SBAT could be used with different purposes:
- As a **sandbox platform**, where `RS backend` service is a simulated `ASPSP`, where SBAT platform will be the `Open Banking REST API provider`.
- As a **customer platform**, where the `ASPSP` will be the `Open Banking REST API provider` and is supposed an interaction with the real `ASPSP` **mainframe**, for that purpose the `ASPSP` needs implement his own RS customer backend.
    -  Implementing the java interfaces provide by `SBAT` that comply with the OB spec versions.
    - Create his own `RS backend` service using any other technology following the `SBAT openAPI convention` to comply with the API contract and integrated properly his own RS backend services.
 
**Requirements**
**Sandbox mode**:
All the implementations to simulate the response elements calculated by `ASPSP` require a new RS backend implementations to:
- Validate the consent before calculated the response fields
- (If the validation success) Calculate the response elements
- Patch the consent with the response elements values.

**Customer mode**:
We suppose that the customer will implement a new RS customer backend services and we will not know about that implementation for that reason we need to keep in mind:
- Provide the operations to patch the consent with the calculated fields by customer
- The customer expect a documentation for consent patch operation

### Design requirements
- [RS backend](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs) Implementation to validate the consent following the expected behaviour defined in OB specs
- [RS backend](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs) Implementation to calculate the response elements after the validation
- Update IDM intent objects to support the expected response elements
- IG Route [60-internal-repo.json](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/tree/master/config/7.0/obdemo-bank/ig/routes/routes-service) is ready to support the consent PATCH operation to update the response elements

#### Design diagrams
![calculate-elements-PISP-final](https://user-images.githubusercontent.com/54277573/180978609-daa9dc5f-3ae6-4708-8f6e-8fbf421803e6.png)

- [Sequence diagram link](https://sequencediagram.org/index.html#initialData=title%20Calculate%20Elements%20for%20Payment%20initiation%0Aactor%20TPP%0Aparticipant%20IG%0Aparticipant%20IDM%0Aparticipantgroup%20%23lightblue%20**RS%20components%2Fservices**%0Aparticipant%20RS-Backend%0A%0Aend%0ATPP--%3EIG%3A%20**Consent**%20Request%3A%20Payment%20initiation%0A%0A%23IG--%3EIDM%3A%20store%3A%20**Consent**%0A%23IDM--%3EIG%3A%20200%20(**consent**%20stored)%0Aend%0AIG-%3ERS-Backend%3A%20**Consent**%20Request%3A%20calculate%20intent%20response%0ARS-Backend-%3ERS-Backend%3A%20**Consent**%3A%20validate%20intent%0ARS-Backend-%3EIG%3A%20sucess%2Ferror%20(%5BError%20object%5D)%0A%3D%3DError%3D%3D%23red%0ARS-Backend-%3EIG%3A%20Response%3A%20**Error**%20object%0A%23IG-%3EIDM%3A%20PATCH%3A%20Consent%20status%20rejected%0A%23IDM-%3EIG%3A%20Patch%20response%3A%20**Consent**%0AIG-%3ETPP%3A%20PISP%20response%3A%20**Error**%20object%20(consent%20rejected%2C%20not%20stored%20in%20IDM)%0A%3D%3DSucess%3D%3D%23lightgreen%0ARS-Backend-%3ERS-Backend%3A%20**Consent**%3A%20calculate%20response%20elements%0A%3D%3DError%3D%3D%23red%0ARS-Backend-%3EIG%3A%20(if%20error%20happens)%20**Error**%20object%0AIG-%3ETPP%3A%20**Error**%20Object%0A%3D%3DSucess%3D%3D%23lightgreen%0ARS-Backend-%3EIG%3A%20response%20calculated%20elements%3A%20**Consent%20with%20calculated%20elements**%0AIG-%3EIDM%3A%20PUT%3A%20**Consent**%20(store%20consent%20with%20calculated%20elements)%0AIDM-%3EIG%3A%20Response%3A%20**Consent**%20(stored%20with%20calculated%20elements)%0A%23IG-%3EIG%3A%20build%20**Consent**%20response%0AIG-%3ETPP%3A%20response%3A%20**Consent**%20response%0A)

### Scope
- Payment initiation consent validation
- Payment initiation consent response

### Acceptance Criteria (DRAFT)
- [x] RS consent validation expected behaviour before calculate the response elements
- [x] RS calculates properly the response elements
- [x] IG supports the consents patch and get
- [x] The IDM intent object is patch with the response elements
- [x] TPP receives the expected response with the response elements included or an error with the consent reject reason 
- [x] Postman test coverage
- [x] Functional test coverage
