### ISSUE TITLE
Examine the existing RCS functionality and add required endpoints to the RS simulator

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#43]
As an Open Banking customer
I want the RS simulator to support the RCS
so that consents can be handled accordingly

## Acceptance criteria
- The existed functionality in the OB Toolkit's RCS is documented
- Supporting endpoints are added to the RS Simulator

## Tasks
- [x] Create Wiki page
- [x] Add DTOs to `securebanking-openbanking-uk-forgerock-datamodel`
- [x] Add `/backoffice/accounts/search/findByUserId` to the RS Simulator

### Release Notes

Affected App: securebanking-openbanking-aspsp-simulator
