### ISSUE TITLE
UI base project: Secure Banking User Interfaces

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#44]
## Story
As a `customer/platform consumer` I want to have the `User Interfaces` so can manage  the resources access such as accept or reject the consents.

<details>
<summary>UIs existing on Openbanking Toolkit (https://github.com/OpenBankingToolkit)</summary>

- [UI openbanking toolkit docs](https://github.com/ForgeCloud/ob-reference-implementation/wiki/UI-guide-for-devs)

### Tools
- [x] [ui-cli](https://github.com/OpenBankingToolkit/openbanking-ui-cli) -> publish [@forgerock/openbanking-ui-cli](https://www.npmjs.com/package/@forgerock/openbanking-ui-cli)
- [ui-customisation](https://github.com/OpenBankingToolkit/openbanking-ui-customization) : [github pages](https://openbankingtoolkit.github.io/openbanking-ui-customization/)
- [x] [ui-common](https://github.com/OpenBankingToolkit/openbanking-ui-common) -> publish [@forgerock/openbanking-ngx-common](https://www.npmjs.com/package/@forgerock/openbanking-ngx-common)

### Apps (Themeable)
- [ASPSP ui](https://github.com/OpenBankingToolkit/openbanking-aspsp/tree/master/forgerock-openbanking-ui)
   - [x] **Bank**: Bank simulation to get account/payment consent (**RCS**)
           - image [eu.gcr.io/openbanking-214714/obri/bank-ui](https://console.cloud.google.com/gcr/images/openbanking-214714/EU/obri/bank-ui)
           - ports 4201:443
   - **Manual-onboarding (register)**: Tpp's registration
           - Image [eu.gcr.io/openbanking-214714/obri/manual-onboarding](https://console.cloud.google.com/gcr/images/openbanking-214714/EU/obri/manual-onboarding)
           - ports 4204:443
- [commons ui](https://github.com/OpenBankingToolkit/openbanking-common/tree/master/forgerock-openbanking-ui) 
   -  [x] **Auth**: OIDC Login/Register pages
           - image [eu.gcr.io/openbanking-214714/obri/auth-ui](https://console.cloud.google.com/gcr/images/openbanking-214714/EU/obri/auth-ui)
           - ports 4203:443
   -  [x] **Swagger**: documentation
           - image [eu.gcr.io/openbanking-214714/obri/swagger-ui](https://console.cloud.google.com/gcr/images/openbanking-214714/EU/obri/swagger-ui)
           - ports 4205:443
- [TPP ui](https://github.com/OpenBankingToolkit/openbanking-tpp/tree/master/forgerock-openbanking-ui)
   -  **Tpp**: Shop simulation
           - tpp app image [eu.gcr.io/openbanking-214714/obri/tpp-ui](https://console.cloud.google.com/gcr/images/openbanking-214714/EU/obri/tpp-ui)
           - ports 4207:80
           - backend image [eu.gcr.io/openbanking-214714/obri/tpp-node](https://console.cloud.google.com/gcr/images/openbanking-214714/EU/obri/tpp-node)
           - ports 5000:8443
   -  **CDR Tpp (money watch)**: simulate a TPP bank aggregator app
           - image cdr-tpp
           - ports 
- [Directory ui](https://github.com/OpenBankingToolkit/openbanking-directory/tree/master/forgerock-openbanking-ui)
   -   **Directory**: Software statement, ASPSPs creation etc.
            - image [eu.gcr.io/openbanking-214714/obri/directory-ui](https://console.cloud.google.com/gcr/images/openbanking-214714/EU/obri/directory-ui)
            - ports 4202:443 
## Customers themes
-  [customers repo](https://github.com/ForgeCloud/ob-customers)
</details>

## Tasks
- [x] Create Secure Banking CLI UI
- [x] Create Secure Banking Common UI
- [x] Create Secure Banking RCS (Bank simulation) UI
- [x] Create Secure Banking Auth UI
- [x] Create Secure Banking Swagger UI
## Acceptance criteria
- [x] Have minimal UI's working against CDK

**Comment by jorgesanchezperez** [comment]
**[PR 1](https://github.com/SecureBankingAcceleratorToolkit/securebanking-ui/pull/1)**
- UI CLI 
   - Origin [ui-cli](https://github.com/OpenBankingToolkit/openbanking-ui-cli)
   - Secure banking destination [ui-cli](https://github.com/SecureBankingAcceleratorToolkit/securebanking-ui/securebanking-cli-ui#readme)
- UI Common
   - Origin [ui-common](https://github.com/OpenBankingToolkit/openbanking-ui-common)
   - Secure banking destination [ui-common](https://github.com/SecureBankingAcceleratorToolkit/securebanking-ui/securebanking-common-ui#readme)

**Comment by jorgesanchezperez** [comment]
**[PR 2](https://github.com/SecureBankingAcceleratorToolkit/securebanking-ui/pull/2)**
- UI RCS (Bank simulation)
   - Origin [Bank UI](https://github.com/OpenBankingToolkit/openbanking-aspsp/tree/master/forgerock-openbanking-ui)
   - Secure banking destination [RSC UI](https://github.com/SecureBankingAcceleratorToolkit/securebanking-ui/securebanking-rcs-ui#readme)

**Comment by jorgesanchezperez** [comment]
**[PR 3](https://github.com/SecureBankingAcceleratorToolkit/securebanking-ui/pull/3)**
- UI AUTH (Bank simulation)
   - Origin [Auth UI](https://github.com/OpenBankingToolkit/openbanking-common/tree/master/forgerock-openbanking-ui)
   - Secure banking destination [Auth UI](https://github.com/SecureBankingAcceleratorToolkit/securebanking-ui/securebanking-auth-ui#readme)

**Comment by jorgesanchezperez** [comment]
**[PR 4](https://github.com/SecureBankingAcceleratorToolkit/securebanking-ui/pull/4)**
- UI Swagger (API documentation)
   - Origin [Swagger UI](https://github.com/OpenBankingToolkit/openbanking-common/tree/master/forgerock-openbanking-ui)
   - Secure banking destination [Swagger UI](https://github.com/SecureBankingAcceleratorToolkit/securebanking-ui/securebanking-auth-ui#readme)
