### ISSUE TITLE
Add remaining payment API endpoints to the RS simulator

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#45]
As an Open Banking customer
I want the RS simulator to support the OB Payments API
so that I can make payments successfully

## Acceptance criteria
- All OB payment endpoints from v3.0 to v3.1.6 are supported.
- The required validation is provided.

## Not covered by this story
- File payment reports are NOT generated (see `PaymentReportFile1Service`).

## Tasks
- [x] Copy interface and controller classes from openbanking-aspsp
- [x] Remove consent related code
- [x] Convert `java.util.Date` instances in "submission" Mongo Documents to `DateTime` instances
- [x] Add `SubmissionStatus` to  "submission" Documents and map to relevant response status
- [x] Create links using new `LinksHelper`
- [x] Add necessary validation
- [x] Check for existing payment submissions for the same consentId
- [x] - Account related data is created (e.g. `scheduledPaymentService.createSchedulePayment(scheduledPayment, pispId)` in the rs-gateway).
- [x] Do this for each version:
   - [x] v3.0
   - [x] v3.1
   - [x] v3.1.1
   - [x] v3.1.2
   - [x] v3.1.3
   - [x] v3.1.4
   - [x] v3.1.5
   - [x] v3.1.6

### Release Notes

Affected App: securebanking-openbanking-aspsp-simulator

**Comment by matt-wills** [comment]
Questions:

- `openbanking-aspsp` uses the consent ID as the ID for a payment submission - is this for convenience? Could it be a problem?
- which file payment report formats need to be supported? Note that the report endpoint is `conditional` (need to investigate).
