### ISSUE TITLE
Add remaining Account API endpoints to the RS simulator

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#46]
As an Open Banking customer
I want the RS simulator to support the OB Accounts API
so that I can retrieve account related information successfully

## Acceptance criteria
- All OB Accounts endpoints from v3.0 to v3.1.6 are supported.

## Not covered by this story
- Account related data is NOT created (e.g. `scheduledPaymentService.createSchedulePayment(scheduledPayment, pispId)` in the rs-gateway).

## Tasks
- [x] Copy interface and controller classes from openbanking-aspsp
- [x] Investigate how to create links (potentially refactoring/replacing `LinksHelper`)
- [x] Do this for each version:
   - [x] v3.0
   - [x] v3.1
   - [x] v3.1.1
   - [x] v3.1.2
   - [x] v3.1.3
   - [x] v3.1.4
   - [x] v3.1.5
   - [x] v3.1.6

### Release Notes

Affected App: securebanking-openbanking-aspsp-simulator
