### ISSUE TITLE
RS: Implementation of optional `GET payment-details` for international standing order

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#471]
### Description
Currently the no-mandatory API `GET /international-standing-orders/{InternationalStandingOrderPaymentId}/payment-details` isn't implemented yet.

**Ref:** https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/international-standing-orders.html

### Task
- [x] Implement Get international standing order details [Here - RS](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs)
- [ ] Add functional tests coverage
- [x] Add postman request tests coverage
- [x] Add Payment details URI for International standing order details in [OBApiReference](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs/blob/master/securebanking-openbanking-uk-rs-simulator-server/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/common/OBApiReference.java).

### Acceptance criteria
- [x] Get international payment details has been implemented
- [ ] All functional tests coverage pass
- [x] All postman tests coverage pass

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/471?planning-poker) with Zenhub @frlaura-jianu @mariantiris

**Comment by mariantiris** [comment]
Found an issue in postman because of an incorrect token used on the payment-details route. The error encountered was invalid_grant_type because the authorization code grant type token was used, instead of the client credentials token (see grant types for each endpoint [here](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/international-standing-orders.html#endpoints)
