### ISSUE TITLE
Functional tests: international standing order consents

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#475]
### Description
Implement the proper functional tests to cover the international standing order consent flow [Here](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-functional-tests)
### Tasks
  - [x] Test coverage international standing order submission with all fields
  - [x] Test coverage international standing order submission with only mandatory fields
  - [x] Test coverage international standing order submission expected errors
  - [x] Add gradle group task to run only the international standing order tests v3.1.8
### Acceptance criteria
- [x] All current functional tests pass.
- [x] The `international standing order` functional tests pass.
- [x] As a developer I can run the a task to run only the `international standing order` functional tests v3.1.8

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/475?planning-poker) with Zenhub @frlaura-jianu @mariantiris
