### ISSUE TITLE
RS backend: Update all payments submission response to add calculated elements values

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#488]
### Description
Currently when a payment is submitted the response doesn't contains the calculated elements.
Update all api version responses with calculated elements that comes from the consent.
### Tasks
- [x] The request body of each submit payment request contains only the values from Initiation, without the Charges or the ExchangeRateInformation from Data. So, we should use the consentId provided in the request body to get from the IDM the whole consent and send it to RS.
- [x] Update RS backend to build the payment submission response with all calculated elements expected by TPP

### Acceptance criteria
- [x] All payments submission response contains the calculated elements expected by tpp.

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/488?planning-poker) with ZenHub @andra-racovita @frlaura-jianu @mariantiris
