### ISSUE TITLE
Update expired (23/08/2022) OB certs for Automating-testing

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#493]
The current certs used for test purposes expires 23/08/2023.
Generate new OB certs for test purposes.

### tasks
- [x] Generate new OB certs (create csr seal and wac and upload them to OB directory to create new seal and wac certs)
- [x] Associated new OB certs with Automating-testing software statement in OB directory
- [x] Update OB-CI-SECRETS with new OB certificates
- [x] Update functional tests dev profile the eidasTestSigningKid with the new OB seal cert KID
- [x] Update OB certs codefresh shared secrets
- [x] Generate new functional tests latest image
