### ISSUE TITLE
IG library: Conversion library IDM objects to OB data model objects

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#495]
## Story
As a Developer I want to pass the OB data model consent object to RS backoffice APIs rather than a String that represents a consent object so that the customer will be able to implement his own RS backoffice APIs more easily and consistently following a standardised documentation.

## Description
Currently the object represents the consent response is stored in IDM and we can deserialise them to OB data model objects but the proper way to build the consent response and other responses expected by the TPP is to translate the consent object stored in IDM to the OB data model defined by the OB spec to ensure that the response match with the expected response defined by the spec.

- The translation from IDM intent object to OB data model will be made in IG through a java library.

The solution will be the creation of a library to translate the IDM intent objects to OB data model consent so that Ig will be able to:
- Call RS backend with the proper OB data model defined by the spec.
- Consistent response with a OB data model instead of a IDM intent object.

## Solution will cover
- RS backend / Backoffice will be able to implement APIs where the request body will be a OB data model
- IG will be able to build a consistent consent responses with a OB data model translating the IDM intent object
- Customer documentation more consistent

## Tasks
- [x] #496
- [x] #497
- [x] #498
- [x] #499
- [x] #500
- [x] #501

## Acceptance criteria
- [ ] Repository for IG libraries created
- [ ] New jar artifact builded and deployed in IG
- [ ] IG uses the new library to translate IDM intent objects to OB data model objects
    - [ ] To call RS backend
    - [ ] To build the responses
- [ ] All tests pass

**Comment by jorgesanchezperez** [comment]
Closed to implement a new solution https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/515
