### ISSUE TITLE
Update uk-gateway Ig version references and clean up

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#523]
## Story

As a developer I want to remain up to date the objects that refers to the current base IG version deployed so that avoid confusions with which is the current version of IG.
- Current version 7.1.0
## Describe the task or solution
Update file names, folders that refers Ig version.

## Tasks
- [ ] Update file names and folders with the current version.
- [ ] Update old references to the current version 7.1.0

## Acceptance criteria
- [ ] All references has been updated
- [ ] The deployment is successful and IG works properly
