### ISSUE TITLE
Register multiple OAUth2 clients with the same cert and SSA

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#538]
## Description
A customer reported that they can register multiple clients with the same cert and SSA and this is not correct behaviour.

**Comment regarding**
Is that not allowed in the spec?? A customer specifically asked for that functionality because TPPs kept losing their client_id, client_secret etc, and then couldn't re-register because we disallowed re-registration of the same software statement..... Then TPPs would ask for their registration to be deleted, but would have no real proof that it was their registration, so we'd have to ask them to sent us a valid SSA from the OB Directory for that software statement to prove they were who they said they were, then we'd have to find the associated OAuth2 registration in AM and manually delete it. In the end we have had a far better time of it since we relaxed that rule, and we did check the dynamic client registration specs and it didn't disallow it...
- Do we want introduce this restriction?

## Task
- [ ] Replicate the case: multiple client with the same cert and the same SSA
- [ ] Create a report regarding the investigation of that case (results etc...)
- [ ] Implement the logic to reject the register when the SSA already register.
- [ ] Add the functional test coverage for this case.

## Acceptance criteria
- [ ] Registers with a SSA already registered are rejected.
- [ ] All tests passed

**Comment by jorgesanchezperez** [comment]
`Is that not allowed in the spec?? A customer specifically asked for that functionality because TPPs kept losing their client_id, client_secret etc, and then couldn't re-register because we disallowed re-registration of the same software statement..... Then TPPs would ask for their registration to be deleted, but would have no real proof that it was their registration, so we'd have to ask them to sent us a valid SSA from the OB Directory for that software statement to prove they were who they said they were, then we'd have to find the associated OAuth2 registration in AM and manually delete it. In the end we have had a far better time of it since we relaxed that rule, and we did check the dynamic client registration specs and it didn't disallow it...`

**Comment by BohoCode** [comment]
I have responded to Christian and Hennes with the observation that we have had customers that have specifically requested us to support the ability for a TPP to create multiple registrations for a single Software Statement. Their reasoning is this:

TPPs often don't have organisation level management of their Open Banking registrations. i.e. individuals are often left to manage Dynamic Client Registration responses, along with important key details such as client_id, an `registration_access_token`. For this reason, customers have found that that they received many support calls from TPPs asking to have their registrations deleted so that they could create a new registration.

**Comment by BohoCode** [comment]
We're now waiting for the customer in question to respond to our response.

**Comment by BohoCode** [comment]
The customer accepts that allowing a customer to perform multiple registrations for the same software statement is a legitimate thing to be able to do.
