### ISSUE TITLE
CDR: provide `registration_access_token` in the response

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#539]
## Description
As a customer I want to store the CDR response to be allow un-register or update my registration using the `registration_access_token` provided in the CDR response.

## Task
- [ ] Update the OAuth2 provider settings to provide the `registration_acess_token` in the CDR response.

## Acceptance criteria
- [ ] The CDR response contains the new expected fields in the response.
- [ ] All tests passed

**Comment by BohoCode** [comment]
Why does this have an 'enhancement' and 'feature' label @jorgesanchezperez ?

**Comment by BohoCode** [comment]
I have just checked this behaviour and the issue is not valid. dev.forgerock.financial's DCR responses do indeed have a `registration_access_token` in.
