### ISSUE TITLE
Implement Read/Write API version validation

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#54]
As an Open Banking customer
I want the RS simulator to fulfil the API version checks
so that the API is compliant with the OB specification

## Background
Initial investigation has revealed missing validation within the OB toolkit's validation of API versions. For example, according to the OB spec:
```
  - Version of consent (cannot create a consent and then access it from a previous version)
  - Version of consent vs version of payment submission
  - Version of payment submission (cannot create a payment submission and then access it from a previous version)
```
Example specification:
  - https://openbankinguk.github.io/read-write-api-site3/v3.1.3/profiles/payment-initiation-api-profile.html#release-management

Investigation has revealed that the payment simulator is checking the versions of callback URLs and event subscriptions, but not payment submissions. The focus of this story is therefore to address the latter.

**N.B.** IG will need to perform consent validation, including comparing it the version of a payment submission.

## Acceptance criteria
- It is not possible to retrieve a payment submission that was created in a newer version of the API being used (a 409 error response is returned).
- All endpoints from v3.0 to v3.1.6 are supported.

## Tasks
- [ ] Investigate the existing validation in `openbanking-aspsp`
- [ ] Determine the level of validation required
- [ ] Add necessary validation (including the version to all repository documents)
- [ ] Do this for each version

### Release Notes

Affected App: securebanking-openbanking-aspsp-simulator
