### ISSUE TITLE
Functional tests: Create File Payment Consent Tests

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#562]
### Description
Implement the proper functional tests to cover the File payment consent flow [Here](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-functional-tests)
### Tasks
  - [x] Test coverage File payment submission with all fields
  - [x] Test coverage File payment submission with only mandatory fields
  - [x] Test coverage File payment submission expected errors
  - [x] Add gradle group task to run only the File payment tests v3.1.8
### Acceptance criteria
- [x] All current functional tests pass.
- [x] The `File payment` functional tests pass.
- [x] As a developer I can run the a task to run only the `File payment` functional tests v3.1.8
