### ISSUE TITLE
Implement offline payment simulation and event notification

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#57]
As an Open Banking customer
I want pending payments to be processed offline and the TPP to be notified
So that I can adequately test event notifications

## Acceptance criteria
- Scheduled tasks complete each type of payment, including the transfer of money.
- Aggregated polling, callbacks and event subscriptions are implemented.

## Tasks
- [ ] Examine existing solution in `forgerock-openbanking-uk-aspsp-rs-mock-payment-simulator-server`.
- [ ] Investigate possible options for triggering and processing offline behaviour.
- [ ] ~Copy required classes from `openbanking-aspsp`~
- [ ] ~Remove consents and deal with payment submissions instead~
- [ ] ~Remove TPP lookups~

### Release Notes

Affected App: securebanking-openbanking-aspsp-simulator

**Comment by matt-wills** [comment]
After discussion with @BohoCode and @jorgesanchezperez this morning, we have decided to defer this as banking simulation isn't required for any of our customers (and is only enabled in the OBIE cluster).

If and when we implement this for SBAT, we can look at possible solutions and alternative options to how the OB toolkit currently does this (for example, utilising some of GCP's serverless options?).

Whatever solution is required, it will need access to:

* The banking simulator (or real customer bank) to:
  - retrieve or update payments (e.g. to set the payment status to `AcceptedSettlementCompleted`).
  - retrieve, update and/or create account/balance/transaction information.
  - retrieve `FREventSubscription` instances by TPP ID (or rather the TPP's application ID?).
  - create pending `FREventNotification` instances.
  - potentially to the discovery API to build up the callback url (though it may be best just to build up the URL, using the version that's stored against the payment).
* IDM to retrieve TPP info.
* IG (or JWKMS if we deploy it) to create a signed JWT (to send to the TPP when performing the callback).
* The TPP via its callback URL.
