### ISSUE TITLE
Create initial RCS API

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#58]
## Story

As a member of the Open Banking team
I want to specify the required endpoints for the RCS
So that the API is understood and the team agrees what's required

## Acceptance criteria
- The required API interface classes are added to the project
- The API interfaces include swagger documentation, allowing the spec to be served dynamically from the application
- A skeleton RCS app starts up
- The main controllers and services are implemented for domestic payment and account consents.
- Calls to external services, such as IDM and AM are stubbed.

## Tasks
- [x] Create sample Spring Boot application
- [x] Add API interfaces with swagger documentation
- [x] Add consent details endpoint and services for a domestic payment and an account
- [x] Add consent decision endpoint and services for a domestic payment and an account
- [x] Add skeleton stubs for clients of external services, such as RS, IDM and AM

### Release Notes
Affected App: securebanking-openbanking-uk-rcs
