### ISSUE TITLE
Provide a full simulation of a Read/Write API endpoint

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#6]
As an Open Banking customer
I want to be able to test my services against a simulated version of an OB Read/Write API endpoint
so that I can be confident my services will work when I switch to a real bank implementation

## Acceptance criteria
- It is possible to save and retrieve a single Open Banking resource - e.g. a Domestic Payment.
- Required information, such as the TPP's details are extracted from the request (e.g. JWT header), rather than the simulator retrieving them from it's own MongoDB instance.
- Instead of using the existing metrics implementation, an appropriate log statement is made, which is easy to identify in the logs (e.g. using a RegEx filter).

## Tasks

- [x]  Replace references to ConsentMetricService in each controller with an appropriate log statement.
- [x]  Add a mechanism to extract required information (such as the Tpp (or client) ID) from a JWT.
- [x]  Remove any references to TppRepository and Tpp from the controller classes.
- [x]  Ensure the controller classes use constructor based injection.

### Release Notes

Affected App: securebanking-openbanking-aspsp-mock
