### ISSUE TITLE
Setup docker-compose for the securebanking apps

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#61]
## Story
As a member of the Open Banking team
I want to be able to spin up the securebanking apps (including mongo and spring cloud config server)
So that I can easily test the apps running locally

## Acceptance criteria
- Configuration is provided by spring cloud config service
- The RCS and RS docker containers start up successfully
- Calls to external services, such as IDM and AM are stubbed using WireMock.

## Tasks
- [x] Create a Spring Cloud Config Service docker image, plus a corresponding git config repo.
- [x] Configure the RS and RCS to use the Spring Cloud Config Service
- [x] Create a WireMock docker image, with stubs for calls to external services, such as IDM and AM.
- [x] Create a docker-compose file that starts up all the required containers, with the required git config.

### Release Notes
Affected Apps:
* securebanking-openbanking-uk-rcs
* securebanking-openbanking-uk-rs
* securebanking-spring-config-server
