### ISSUE TITLE
Support consent UI for other consent types within the RCS

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#66]
## Story

As an Open Banking customer
I want to be able to test the consent UI against each payment type
so that I can be confident the RCS will work when integrated with real services

## Acceptance criteria

- All payment types (domestic, international and files) are supported.
- Accounts access consents and funds confirmation consents are supported.

## Tasks

- [ ]  Add the required consent types to securebanking-openbanking-uk-forgerock-datamodel.
- [ ]  Support each consent type within the RCS
- [ ] Test each consent type within the UI (using docker and wiremock locally for now).

### Release Notes

Affected App: securebanking-openbanking-uk-rcs
