### ISSUE TITLE
Implement v3.1.7 of the Read/Write API

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#73]
## Story

As a customer of the Secure Access Banking Toolkit
I want to be able to use v3.1.7 of the Read/Write API
so that I can be sure I am compliant with the latest OB specifications.

## Acceptance criteria

- v3.1.7 of the Read/Write API has been implements for:
** Payment Initiation
** Accounts
** Funds Confirmation
** Aggregated Polling
** Callback URL
** Events Subscription
- I can see the required v3.1.7 URLs in the Discovery API.

## Tasks

- [x] Analyse functional changes in spec and present list of issues to implement
- [x] Generate new uk-datamodel classes.
- [x] Generate new controller classes/interfaces with relevant changes.
- [x] Update config files (e.g. RS discovery config, with active/inactive API versions).
- [x] Update datamodel converter classes.
- [x] Update functional tests - add tests for new fields
- [x] Check discovery endpoint
- [x] Update SBAT postman collection

### Release Notes

Affected App: securebanking-openbanking-uk-rs
