### ISSUE TITLE
Variable Recurring Payments (VRPs) for v3.1.8

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#75]
## Story

As a customer of the Secure Banking Access Toolkit
I want to be able to use VRPs
so that I can be sure I am compliant with the latest OB specifications.

## Acceptance criteria

- v3.1.8 of VRPs is supported.
- I can see the required v3.1.8 VRP URLs in the RS Discovery API.

## Tasks

- [ ] Analyse functional changes in spec and present list of issues to implement
- [ ] Generate new uk-datamodel classes.
- [ ] Generate new controller classes/interfaces with relevant changes.
- [ ] Implement datamodel converter classes.
- [ ] Add new functional tests (covered by equivalent OB Toolkit story)
- [ ] Check discovery endpoint
- [ ] Create Postman tests in SBAT collection

### Release Notes

Affected Apps:
* securebanking-openbanking-uk-rs

**Comment by jorgesanchezperez** [comment]
Duplicated.
Close to work on https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/203
