### ISSUE TITLE
URLs from the RS Simulator should be derived from X-Forwarded headers

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#78]
## Story

As a TPP using the RS API
I want URLs to contain the externally facing domain
so that I know which URLs to use

## Acceptance criteria
* If `X-Forwarded` headers are provided in a request, then URLs from these endpoints should be derived from them:
** the Discovery endpoint
** the Swagger endpoint
** Self links to resources within the Payments, Events and Funds Confirmation APIs
* If no `X-Forwarded` headers are provided, then the URLs will contain the default Spring Boot root: (e.g. `http://localhost:8080').
* The Accounts API will continue to rely upon the `x-ob-url` header, which must be provided in each request.

## Tasks

_OPTIONAL_
- [ ] Change "self" links to resources.
- [ ] Change Discovery links.
- [ ] Change URLs within the swagger endpoint.

### Release Notes

Affected App: `securebanking-openbanking-uk-rs-simulator`
